name: 'action-semantic-release'
description: 'Github action to release projects using semantic-release'
author: 'quike'

branding:
  icon: activity
  color: yellow

inputs:
  dry-run:
    description:
      'The objective of the dry-run mode is to get a preview of the pending release. Dry-run mode skips the following
      steps: prepare, publish, addChannel, success and fail. In addition to this it prints the next version and release
      notes to the console.'
    required: false
    default: 'false'
  working-path:
    description: 'Working directory where configuration file lives'
    required: false
    default: '${{ github.workspace }}'
  debug-mode:
    description: 'Enable verbosity mode'
    required: false
    default: 'false'
  event-name:
    description: 'Defines the event triggering the run.'
    default: '${{ github.event_name }}'
  add-summary:
    description: 'Create a GitHub Job Summary.'
    required: false
    default: 'true'
  default-config-enabled:
    description: 'Uses predefined configuration if config files are not present.'
    required: false
    default: 'true'
  default-preset-info:
    description:
      'For presets that expects a configuration object, such as conventionalcommits, the presetConfig & releaseRules
      options must be set. Some basic predefined configuration is available hardcoded in semanti-release, but for
      conventionalcommits if no presetConfig and releaseRules are passed, it falls back to the default preset
      configuration: angular ignoring the input.'
    required: false
    default: 'true'
  floating-tags:
    description: 'Create floating tags from major and minor versions after release.'
    required: false
    default: 'false'

outputs:
  release-published:
    description: 'True if a new release is performed, false otherwise.'
  release-version:
    description: 'New version or current version if not released, example: 1.2.3'
  release-major:
    description: 'New Major version of the semver, example: 1.'
  release-minor:
    description: 'New Minor version of the semver, example: .2.'
  release-patch:
    description: 'New Path version of the semver, example: .3'
  release-type:
    description: 'Type of semver promotion: major, minor or patch.'
  release-git-head:
    description: 'SHA value associated to release commit.'
  release-git-tag:
    description: 'Git Tag associated to release commit.'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/quike/action-semantic-release:2'
  env:
    DRY_RUN: ${{ inputs.dry-run }}
    DEBUG_MODE: ${{ inputs.debug-mode }}
    EVENT_NAME: ${{ inputs.event-name }}
    WORKING_PATH: ${{ inputs.working-path }}
    DEFAULT_CONFIG_ENABLED: ${{ inputs.default-config-enabled }}
    DEFAULT_PRESET_INFO: ${{ inputs.default-preset-info }}
  args:
    - ${{ inputs.working-path }}
    - ${{ inputs.dry-run }}
    - ${{ inputs.debug-mode }}
    - ${{ inputs.add-summary }}
    - ${{ inputs.default-config-enabled }}
    - ${{ inputs.default-preset-info }}
    - ${{ inputs.floating-tags }}
