name: Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - name: Install Dependencies
        id: npm-ci
        run: npm ci
      - name: Check Format
        id: npm-format-check
        run: npm run format:check
      - name: Lint
        id: npm-lint
        run: npm run lint
      - name: Set Test Environment
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "To test action, we are going to change stable image to internal Dockefile."
            grep "docker" < ./action.yml
            YQ_VERSION=v4.34.1
            sudo wget "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" -O /usr/local/bin/yq
            yq -i '.runs.image = "Dockerfile"' ./action.yml
            echo "Now action under test should point to internal image."
            grep "Dockerfile" < ./action.yml
          fi
      - name: Release
        id: release
        uses: ./
        with:
          debug-mode: true
          dry-run: false
          default-config-enabled: true
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
      - name: Get the output
        run: |
          echo "The release version is ${{ steps.release.outputs.release-version }}"
          echo "The relese sha is ${{ steps.release.outputs.release-git-head }}"
